export default {
  grid: {
    container: '130rem',
    gutter: '3rem',
  },
  border: {
    radius: {
      normal: '0.4rem',
      large: '1.5rem',
    },
  },
  box: {
    shadow: '0px 4px 8px rgba(0, 0, 0, 0.1)',
  },
  font: {
    family:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    light: 300,
    normal: 400,
    semiBold: 600,
    bold: 700,
    sizes: {
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.8rem',
    },
  },
  colors: {
    lightPrimary: '#FF8084',
    primary: '#ED1C24',
    darkPrimary: '#B30007',
    lightSecondary: '#808080',
    secondary: '#666666',
    darkSecondary: '#333333',
    success: '#d0f5d2',
    darkSuccess: '#98eb9d',
    lightSuccess: '#D0F5D2',
    warning: '#fff9ea',
    darkWarning: '#ffe5a1',
    lightWarning: '#FFF9EA',
    danger: '#f5d0d0',
    darkDanger: '#f2bdbd',
    mainBg: '#F2F2F2',
    white: '#FFFFFF',
    black: '#030517',
    lightGray: '#F2F2F2',
    gray: '#CCCCCC',
    semiDarkGray: '#e6e6e6',
    darkGray: '#AAAAAA',
  },
  spacings: {
    xxxsmall: '0.4rem',
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
} as const;
